#!/bin/bash
gcc -E $CFILE -o c
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~~
~
~
~
~
~
0-preprocessor[+] [unix] (15:43 14/04/2022)                                            2,1 All
-- INSERT --

